//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWideImportersEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.Orders = new HashSet<Order>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int City_Key { get; set; }
        public int WWI_City_ID { get; set; }
        public string City1 { get; set; }
        public string State_Province { get; set; }
        public string Country { get; set; }
        public string Continent { get; set; }
        public string Sales_Territory { get; set; }
        public string Region { get; set; }
        public string Subregion { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public long Latest_Recorded_Population { get; set; }
        public System.DateTime Valid_From { get; set; }
        public System.DateTime Valid_To { get; set; }
        public int Lineage_Key { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
