//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWideImportersEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Staging
    {
        public int Customer_Staging_Key { get; set; }
        public int WWI_Customer_ID { get; set; }
        public string Customer { get; set; }
        public string Bill_To_Customer { get; set; }
        public string Category { get; set; }
        public string Buying_Group { get; set; }
        public string Primary_Contact { get; set; }
        public string Postal_Code { get; set; }
        public System.DateTime Valid_From { get; set; }
        public System.DateTime Valid_To { get; set; }
    }
}
