//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWideImportersEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineage
    {
        public int Lineage_Key { get; set; }
        public System.DateTime Data_Load_Started { get; set; }
        public string Table_Name { get; set; }
        public Nullable<System.DateTime> Data_Load_Completed { get; set; }
        public bool Was_Successful { get; set; }
        public System.DateTime Source_System_Cutoff_Time { get; set; }
    }
}
