//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWideImportersEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement_Staging
    {
        public long Movement_Staging_Key { get; set; }
        public Nullable<System.DateTime> Date_Key { get; set; }
        public Nullable<int> Stock_Item_Key { get; set; }
        public Nullable<int> Customer_Key { get; set; }
        public Nullable<int> Supplier_Key { get; set; }
        public Nullable<int> Transaction_Type_Key { get; set; }
        public Nullable<int> WWI_Stock_Item_Transaction_ID { get; set; }
        public Nullable<int> WWI_Invoice_ID { get; set; }
        public Nullable<int> WWI_Purchase_Order_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> WWI_Stock_Item_ID { get; set; }
        public Nullable<int> WWI_Customer_ID { get; set; }
        public Nullable<int> WWI_Supplier_ID { get; set; }
        public Nullable<int> WWI_Transaction_Type_ID { get; set; }
        public Nullable<System.DateTime> Last_Modifed_When { get; set; }
    }
}
