//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWideImportersEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long Order_Key { get; set; }
        public int City_Key { get; set; }
        public int Customer_Key { get; set; }
        public int Stock_Item_Key { get; set; }
        public System.DateTime Order_Date_Key { get; set; }
        public Nullable<System.DateTime> Picked_Date_Key { get; set; }
        public int Salesperson_Key { get; set; }
        public Nullable<int> Picker_Key { get; set; }
        public int WWI_Order_ID { get; set; }
        public Nullable<int> WWI_Backorder_ID { get; set; }
        public string Description { get; set; }
        public string Package { get; set; }
        public int Quantity { get; set; }
        public decimal Unit_Price { get; set; }
        public decimal Tax_Rate { get; set; }
        public decimal Total_Excluding_Tax { get; set; }
        public decimal Tax_Amount { get; set; }
        public decimal Total_Including_Tax { get; set; }
        public int Lineage_Key { get; set; }
    
        public virtual City City { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Date Date { get; set; }
        public virtual Date Date1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Stock_Item Stock_Item { get; set; }
    }
}
