//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWideImportersEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Staging
    {
        public long Purchase_Staging_Key { get; set; }
        public Nullable<System.DateTime> Date_Key { get; set; }
        public Nullable<int> Supplier_Key { get; set; }
        public Nullable<int> Stock_Item_Key { get; set; }
        public Nullable<int> WWI_Purchase_Order_ID { get; set; }
        public Nullable<int> Ordered_Outers { get; set; }
        public Nullable<int> Ordered_Quantity { get; set; }
        public Nullable<int> Received_Outers { get; set; }
        public string Package { get; set; }
        public Nullable<bool> Is_Order_Finalized { get; set; }
        public Nullable<int> WWI_Supplier_ID { get; set; }
        public Nullable<int> WWI_Stock_Item_ID { get; set; }
        public Nullable<System.DateTime> Last_Modified_When { get; set; }
    }
}
