//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWideImportersEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public long Purchase_Key { get; set; }
        public System.DateTime Date_Key { get; set; }
        public int Supplier_Key { get; set; }
        public int Stock_Item_Key { get; set; }
        public Nullable<int> WWI_Purchase_Order_ID { get; set; }
        public int Ordered_Outers { get; set; }
        public int Ordered_Quantity { get; set; }
        public int Received_Outers { get; set; }
        public string Package { get; set; }
        public bool Is_Order_Finalized { get; set; }
        public int Lineage_Key { get; set; }
    
        public virtual Date Date { get; set; }
        public virtual Stock_Item Stock_Item { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
