//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWideImportersEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Staging
    {
        public int Supplier_Staging_Key { get; set; }
        public int WWI_Supplier_ID { get; set; }
        public string Supplier { get; set; }
        public string Category { get; set; }
        public string Primary_Contact { get; set; }
        public string Supplier_Reference { get; set; }
        public int Payment_Days { get; set; }
        public string Postal_Code { get; set; }
        public System.DateTime Valid_From { get; set; }
        public System.DateTime Valid_To { get; set; }
    }
}
