//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWideImportersEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Staging
    {
        public long Transaction_Staging_Key { get; set; }
        public Nullable<System.DateTime> Date_Key { get; set; }
        public Nullable<int> Customer_Key { get; set; }
        public Nullable<int> Bill_To_Customer_Key { get; set; }
        public Nullable<int> Supplier_Key { get; set; }
        public Nullable<int> Transaction_Type_Key { get; set; }
        public Nullable<int> Payment_Method_Key { get; set; }
        public Nullable<int> WWI_Customer_Transaction_ID { get; set; }
        public Nullable<int> WWI_Supplier_Transaction_ID { get; set; }
        public Nullable<int> WWI_Invoice_ID { get; set; }
        public Nullable<int> WWI_Purchase_Order_ID { get; set; }
        public string Supplier_Invoice_Number { get; set; }
        public Nullable<decimal> Total_Excluding_Tax { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<decimal> Total_Including_Tax { get; set; }
        public Nullable<decimal> Outstanding_Balance { get; set; }
        public Nullable<bool> Is_Finalized { get; set; }
        public Nullable<int> WWI_Customer_ID { get; set; }
        public Nullable<int> WWI_Bill_To_Customer_ID { get; set; }
        public Nullable<int> WWI_Supplier_ID { get; set; }
        public Nullable<int> WWI_Transaction_Type_ID { get; set; }
        public Nullable<int> WWI_Payment_Method_ID { get; set; }
        public Nullable<System.DateTime> Last_Modified_When { get; set; }
    }
}
