//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWideImportersEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long Transaction_Key { get; set; }
        public System.DateTime Date_Key { get; set; }
        public Nullable<int> Customer_Key { get; set; }
        public Nullable<int> Bill_To_Customer_Key { get; set; }
        public Nullable<int> Supplier_Key { get; set; }
        public int Transaction_Type_Key { get; set; }
        public Nullable<int> Payment_Method_Key { get; set; }
        public Nullable<int> WWI_Customer_Transaction_ID { get; set; }
        public Nullable<int> WWI_Supplier_Transaction_ID { get; set; }
        public Nullable<int> WWI_Invoice_ID { get; set; }
        public Nullable<int> WWI_Purchase_Order_ID { get; set; }
        public string Supplier_Invoice_Number { get; set; }
        public decimal Total_Excluding_Tax { get; set; }
        public decimal Tax_Amount { get; set; }
        public decimal Total_Including_Tax { get; set; }
        public decimal Outstanding_Balance { get; set; }
        public bool Is_Finalized { get; set; }
        public int Lineage_Key { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Date Date { get; set; }
        public virtual Payment_Method Payment_Method { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Transaction_Type Transaction_Type { get; set; }
    }
}
